fs = require 'fs'
sys = require 'sys'
{exec} = require 'child_process'

appFiles = [
    'board', 'solver', 'main'
]

task 'build', 'Build a single javascript file from our various coffeescript files', ->
    appContents = new Array remaining = appFiles.length
    for file, index in appFiles then do (file, index) ->
        fs.readFile "src/#{file}.coffee", 'utf8', (err, fileContents) ->
            throw err if err
            appContents[index] = fileContents
            process() if --remaining is 0
    exec 'coffee --compile src/main.coffee', (err, stdout, stderr) ->
        throw err if err
        sys.puts 'Compiled main.coffee'
    process = ->
        fs.writeFile 'lib/sudoku.coffee', appContents.join('\n\n'), 'utf8', (err) ->
            throw err if err
            exec 'coffee --compile lib/sudoku.coffee', (err, stduout, stderr) ->
                throw err if err
                /*sys.puts stdout + stderr*/
                fs.unlink 'lib/sudoku.coffee', (err) ->
                    throw err if err
                    sys.puts 'Compiled sudoku.coffee'
